// Build-time generator: rasterizes Natural Earth 110m landmass into a dot grid
// for the About hero delivery map. Run: node gen-map.js  →  writes world-dots.js
const fs = require('fs');

const LON_STEP = 3.6, LAT_STEP = 3.6, LAT_TOP = 74, LAT_BOTTOM = -56;

async function main() {
  const res = await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json');
  if (!res.ok) throw new Error('fetch failed: ' + res.status);
  const topo = JSON.parse(await res.text());
  const [sx, sy] = topo.transform.scale, [tx, ty] = topo.transform.translate;
  const arcs = topo.arcs.map(arc => {
    let x = 0, y = 0;
    return arc.map(([dx, dy]) => { x += dx; y += dy; return [x * sx + tx, y * sy + ty]; });
  });
  const ringPoints = idxs => idxs.flatMap(i => (i < 0 ? [...arcs[~i]].reverse() : arcs[i]));
  const land = topo.objects.land;
  const geoms = land.type === 'GeometryCollection' ? land.geometries : [land];
  const polys = [];
  for (const g of geoms) {
    const polyList = g.type === 'Polygon' ? [g.arcs] : g.arcs;
    for (const poly of polyList) polys.push({ outer: ringPoints(poly[0]), holes: poly.slice(1).map(ringPoints) });
  }
  const inRing = (lon, lat, pts) => {
    let inside = false;
    for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
      const [xi, yi] = pts[i], [xj, yj] = pts[j];
      if (((yi > lat) !== (yj > lat)) && (lon < (xj - xi) * (lat - yi) / (yj - yi) + xi)) inside = !inside;
    }
    return inside;
  };
  const isLand = (lon, lat) => {
    for (const p of polys) {
      if (inRing(lon, lat, p.outer)) {
        let inHole = false;
        for (const h of p.holes) if (inRing(lon, lat, h)) { inHole = true; break; }
        if (!inHole) return true;
      }
    }
    return false;
  };

  const cols = Math.round(360 / LON_STEP), rows = Math.round((LAT_TOP - LAT_BOTTOM) / LAT_STEP);
  const rowsOut = [];
  let landDots = 0;
  for (let r = 0; r < rows; r++) {
    const lat = LAT_TOP - (r + 0.5) * LAT_STEP;
    let line = '';
    for (let c = 0; c < cols; c++) {
      const lon = -180 + (c + 0.5) * LON_STEP;
      const hit = isLand(lon, lat);
      if (hit) landDots++;
      line += hit ? '#' : '.';
    }
    rowsOut.push(line);
  }
  fs.writeFileSync('world-dots.js',
    '// Auto-generated by gen-map.js — Natural Earth 110m land rasterized to a dot grid.\n' +
    `window.WORLD_DOT_GRID={latTop:${LAT_TOP},latSpan:${LAT_TOP - LAT_BOTTOM},rows:${JSON.stringify(rowsOut)}};\n`);
  console.log('land dots:', landDots, '| grid:', cols + 'x' + rows);
  console.log(rowsOut.map(l => l.replace(/#/g, '\u2588').replace(/\./g, ' ')).join('\n'));
}
main().catch(e => { console.error(e); process.exit(1); });
